"""
Constants used throughout the scraper.
"""

# Browser Configuration
BROWSER_VIEWPORT_WIDTH = 1920
BROWSER_VIEWPORT_HEIGHT = 1080

# Timeouts (milliseconds)
TIMEOUT_COOKIE_ACCEPT = 1000
TIMEOUT_SCROLL = 1500
TIMEOUT_CLOSED_STORES_CLICK = 500
TIMEOUT_CLOSED_STORES_LOAD = 3000
TIMEOUT_CLOSED_STORES_TEXT = 5000
TIMEOUT_POPUP_CLOSE = 500
TIMEOUT_POPUP_ESCAPE = 1000
TIMEOUT_DYNAMIC_CONTENT = 3000
TIMEOUT_API_CALLS = 3000
TIMEOUT_OFFERS_CLICK = 1500
TIMEOUT_PIZZA_ITEM_CLICK = 2000
TIMEOUT_MODAL_STEP_CLICK = 1500
TIMEOUT_DEEP_SCAN_CLICK = 1000
TIMEOUT_MODAL_CLOSE = 500
TIMEOUT_LAZY_LOAD = 1000

# Iteration Limits
SCROLL_ITERATIONS = 3
LAZY_LOAD_SCROLL_ITERATIONS = 5
RATING_CANDIDATE_LIMIT = 10
CM_ELEMENT_ITERATION_LIMIT = 10

# Validation Bounds
RATING_MIN = 1.0
RATING_MAX = 5.0
PRICE_MIN_FILTER = 5.0

# Business Logic
TOP_DEALS_LIMIT = 5
DEAL_NAME_MAX_LENGTH = 100
